from __future__ import annotations
import inspect, json
from pathlib import Path
import numpy as np
import pandas as pd
from run_theme_review_backtest import ThemeReviewBT, FILL

SYS=Path('july_theme_system')
rules=json.loads((SYS/'playbook_rules_v1.json').read_text(encoding='utf-8'))

# 1) Static source boundaries: execution engine must not read old strategy folders or August price data.
src=(SYS/'run_theme_review_backtest.py').read_text(encoding='utf-8')+(SYS/'run_theme_review_production.py').read_text(encoding='utf-8')
assert "Path('2026-07')" in src, 'July ROOT not explicit'
assert "Path('2026-08')" not in src and '2026-08/' not in src, 'August price path forbidden'
assert "Path('backtest')" not in src and "Path(\"backtest\")" not in src, 'Old backtest path forbidden'

# 2) Confirmation minute and fill minute are distinct and forward-moving.
assert FILL == {'09:45':'09:46','10:00':'10:01','10:30':'10:31'}
assert rules['execution']['confirmation_then_fill']=='next-minute open'
assert rules['execution']['t_plus_one'] is True

bt=ThemeReviewBT()

# 3) Institutional status/limit handling uses absolute down-limit magnitude.
status=pd.DataFrame([{
    'code':'000001','is_st':False,'is_star_st':False,'is_new_listing_initial':False,'is_suspended':False,
    'price_limit_up_pct':10.0,'price_limit_down_pct':-10.0
}]).set_index('code',drop=False)
ok,reason=bt.can_trade_stock(status,'000001','SELL',9.01,10.0,pd.Series({'volume':100.0}))
assert ok, 'A price above the -10% floor should be sellable'
ok,reason=bt.can_trade_stock(status,'000001','SELL',9.00,10.0,pd.Series({'volume':100.0}))
assert not ok and reason=='locked_limit_down', 'Exact down-limit should be blocked conservatively'

# 4) New listing is observation-only, never accidentally traded.
status_new=status.copy(); status_new.loc['000001','is_new_listing_initial']=True
ok,reason=bt.can_trade_stock(status_new,'000001','BUY',10.5,10.0,pd.Series({'volume':100.0}))
assert not ok and reason=='is_new_listing_initial'

# 5) Same-day sell after entry is prohibited by the sell() path itself.
bt.pos['000001']={'code':'000001','name':'TEST','theme':'T','role':'theme_leader','mode':'leader_weak_to_strong','entry_date':'2026-07-02','obs_time':'09:45','entry_time':'09:46','entry_price':10.0,'shares':100,'basis':1000.3,'hold_days':0,'max_price':10.0,'min_price':10.0,'last_mark':10.0,'entry_phase':'x','theme_state_entry':'confirm','priority_entry':1,'scale_entry':1.0}
daily=pd.DataFrame([{'code':'000001','prev_close':10.0}]).set_index('code',drop=False)
bar=pd.Series({'open':10.2,'volume':100.0})
ok,reason=bt.sell('2026-07-02','10:01','000001',bar,status,daily,'unit_test')
assert not ok and reason=='T+1', 'Same-day sell must be rejected'

# 6) Causal learning policy: no threshold changes; only future half-size/pause state.
assert rules['learning']['single_trade_threshold_tuning_forbidden'] is True
assert rules['learning']['rule_change_min_closed_samples']>=8
assert rules['learning']['july_end_retuning_forbidden'] is True

# 7) Every non-cash playbook has explicit observation windows and next-minute entry windows.
for name,spec in rules['playbooks'].items():
    if name=='cash': continue
    assert len(spec['entry_windows'])==len(spec['observation_windows'])
    for obs,entry in zip(spec['observation_windows'],spec['entry_windows']):
        assert FILL[obs]==entry, f'{name}: {obs} must fill at next minute open {FILL[obs]}, got {entry}'

# 8) Core universe cannot be generated by price ranking: it must come from prior web context tables.
cand_src=inspect.getsource(ThemeReviewBT.candidate_table)
assert "self.role_rows(date)" in cand_src and "self.theme_rows(date)" in cand_src
assert 'nlargest' not in cand_src and '.rank(' not in cand_src, 'Core candidates must not be reconstructed from ex-post price ranking'

# 9) Mode selection is deterministic by predeclared theme priority/role/mode order, never future PnL.
entry_src=inspect.getsource(ThemeReviewBT.process_entries)
assert 'sorted(passed' in entry_src
assert 'pnl' not in entry_src.lower() and 'future' not in entry_src.lower()

print(json.dumps({
    'status':'PASS',
    'july_only_price_boundary':True,
    'old_backtest_forbidden':True,
    'next_minute_execution_verified':True,
    't_plus_one_verified':True,
    'signed_limit_rule_verified':True,
    'new_listing_block_verified':True,
    'prior_context_core_universe_verified':True,
    'causal_learning_contract_verified':True
},ensure_ascii=False,indent=2))
